  
  export const coreStatNames = ["Str", "Dex", "Agi", "Vit", "Int", "Mnd", "Chr"];

  export const combatStatNames = [
    "DMG",
    "Delay",
    "Accuracy",
    "Attack",
    "DA",
    "TA",
    "QA",
    "GearHaste",
    "StoreTP",
    "WeaponSkillDamage",
    "ConserveTP",
    "RangedAccuracy",
    "RangedAttack",
    "DADamage%",
    "DualWield",
    "PDL",
    "WeaponSkillAccuracy",
    "SkillchainBonus",
    "CritRate",
    "TPBonus",
    "MartialArts",
    "SubtleBlow",
    "SubtleBlowII",
    "CritDamage",
  ];

  export const magicStatNames = [
    "MagicAccuracy",
    "MagicAttack",
    "MagicBurstDamage",
    "ElementalBonus",
    "MagicBurstAccuracy",
    "MagicBurstDamageII",
    "MagicDamage",
    "EarthElementalBonus",
    "EnSpellDamage",
  ];

  export const defenseStatNames = [
    "DT",
    "MDT",
    "PDT",
    "Defense",
    "Evasion",
    "MagicEvasion",
    "MagicDefense",
  ];

  export const statSkillNames = [
    "SwordSkill",
    "AxeSkill",
    "GreatSwordSkill",
    "GreatAxeSkill",
    "DaggerSkill",
    "HandToHandSkill",
    "StaffSkill",
    "PolearmSkill",
    "GreatKatanaSkill",
    "KatanaSkill",
    "ClubSkill",
    "ArcherySkill",
    "MarksmanshipSkill",
    "ThrowingSkill",
    "HealingSkill",
    "ElementalMagicSkill",
    "EnhancingSkill",
    "EnfeeblingSkill",
    "ElementalSkill",
    "DarkSkill",
    "DivineSkill",
    "BlueMagicSkill",
    "SummoningSkill",
    "NinjutsuSkill",
    "SingingSkill",
    "StringSkill",
    "WindSkill",
    "MagicAccuracySkill",
  ];

  export const petStatNames = [
    "Pet:Accuracy",
    "Pet:MagicAccuracy",
    "Pet:RangedAccuracy",
    "Pet:Str",
    "Pet:Dex",
    "Pet:Agi",
    "Pet:Vit",
    "Pet:Int",
    "Pet:Mnd",
    "Pet:Chr",
    "Pet:Attack",
    "Pet:MagicAttack",
    "Pet:RangedAttack",
    "Pet:SubtleBlow",
    "AutomatonCombatSkill",
    "Pet:GearHaste",
    "Pet:DA",
    "Pet:DT",
  ];
  