// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FFXIComp.Api.Migrations
{
    [DbContext(typeof(GearDbContext))]
    partial class GearDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("FFXIComp.Api.Models.GearItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GearItems");
                });

            modelBuilder.Entity("FFXIComp.Api.Models.GearItemJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GearItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GearItemId");

                    b.ToTable("GearItemJobs");
                });

            modelBuilder.Entity("FFXIComp.Api.Models.GearStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GearItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GearItemId");

                    b.ToTable("GearStats");
                });

            modelBuilder.Entity("FFXIComp.Api.Models.GearItemJob", b =>
                {
                    b.HasOne("FFXIComp.Api.Models.GearItem", "GearItem")
                        .WithMany("GearItemJobs")
                        .HasForeignKey("GearItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GearItem");
                });

            modelBuilder.Entity("FFXIComp.Api.Models.GearStat", b =>
                {
                    b.HasOne("FFXIComp.Api.Models.GearItem", "GearItem")
                        .WithMany("GearStats")
                        .HasForeignKey("GearItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GearItem");
                });

            modelBuilder.Entity("FFXIComp.Api.Models.GearItem", b =>
                {
                    b.Navigation("GearItemJobs");

                    b.Navigation("GearStats");
                });
#pragma warning restore 612, 618
        }
    }
}
