Balder_Earring = {"Name":"Balder Earring +1", "Attack":10, "Store TP":3, "QA":1, "Jobs":all_jobs}
Brutal_Earring = {"Name":"Brutal Earring", "DA":5, "Store TP":1, "Jobs":all_jobs}
Cessance_Earring = {"Name":"Cessance Earring", "Accuracy":6, "DA":3, "Store TP":3, "Jobs":all_jobs}
Crematio_Earring = {"Name":"Crematio Earring", "Magic Attack":6, "Magic Damage":6, "Jobs":all_jobs}
Crepuscular_Earring = {"Name":"Crepuscular Earring", "Accuracy":10, "Ranged Accuracy":10, "Magic Accuracy":10, "Store TP":5, "Jobs":all_jobs}
Dedition_Earring = {"Name":"Dedition Earring", "Accuracy":-10, "Ranged Accuracy":-10, "Attack":-10, "Ranged Attack":-10, "Store TP":8, "Jobs":all_jobs}
Dignitary_Earring = {"Name":"Dignitary's Earring", "Accuracy":10, "Magic Accuracy":10, "Store TP":3, "Subtle Blow":5, "Jobs":all_jobs}
Eabani_Earring = {"Name":"Eabani Earring", "Evasion":15, "Magic Evasion":8, "Dual Wield":4, "Jobs":all_jobs}
Friomisi_Earring = {"Name":"Friomisi Earring", "Magic Attack":10, "Jobs":all_jobs}
Ishvara_Earring = {"Name":"Ishvara Earring", "Weapon Skill Damage":2, "Jobs":all_jobs}
Lugra_Earring_Aug = {"Name":"Lugra Earring +1 R15 (day)", "STR":0+8, "DEX":0+8, "VIT":0+8, "INT":0+8, "DA":3, "Jobs":["war", "pld", "drk", "bst", "sam", "nin"]}
Lugra_Earring_Aug2 = {"Name":"Lugra Earring +1 R15 (night)", "STR":8+8, "DEX":8+8, "VIT":8+8, "INT":8+8, "DA":3, "Jobs":["war", "pld", "drk", "bst", "sam", "nin"]}
Mache_Earring = {"Name":"Mache Earring +1A", "DEX":8, "Accuracy":10, "DA":2, "Martial Arts":13, "Jobs":all_jobs}
Moonshade_Earring = {"Name":"Moonshade Earring", "Accuracy":4, "TP Bonus":250, "Jobs":all_jobs}
Odr_Earring = {"Name":"Odr Earring", "DEX":10, "Accuracy":10, "Crit Rate":5, "Jobs":["mnk", "thf", "rng", "nin", "blu", "cor", "dnc", "run"]}
Schere_Earring0 = {"Name":"Schere Earring R0", "Rank":0, "STR":5, "DA":6, "Accuracy":0, "Attack":0, "Store TP":0, "Subtle Blow":3, "Jobs":["war", "mnk", "drk", "sam", "pup"]}
Schere_Earring15 = {"Name":"Schere Earring R15", "Rank":15, "STR":5, "DA":6, "Accuracy":0+15, "Attack":0, "Store TP":0, "Subtle Blow":3, "Jobs":["war", "mnk", "drk", "sam", "pup"]}
Schere_Earring20 = {"Name":"Schere Earring R20", "Rank":20, "STR":5, "DA":6, "Accuracy":0+15, "Attack":0+5, "Store TP":0, "Subtle Blow":3, "Jobs":["war", "mnk", "drk", "sam", "pup"]}
Schere_Earring25 = {"Name":"Schere Earring R25", "Rank":25, "STR":5, "DA":6, "Accuracy":0+15, "Attack":0+10, "Store TP":0+3, "Subtle Blow":3, "Jobs":["war", "mnk", "drk", "sam", "pup"]}
Schere_Earring30 = {"Name":"Schere Earring R30", "Rank":30, "STR":5, "DA":6, "Accuracy":0+15, "Attack":0+15, "Store TP":0+5, "Subtle Blow":3, "Jobs":["war", "mnk", "drk", "sam", "pup"]}
Static_Earring = {"Name":"Static Earring", "MND":2, "Magic Burst Damage":5, "Jobs":all_jobs}
Suppanomimi = {"Name":"Suppanomimi", "AGI":2, "Dual Wield":5, "Sword Skill":5, "Jobs":all_jobs}
Telos_Earring = {"Name":"Telos Earring", "Accuracy":10, "Attack":10, "Ranged Accuracy":10, "Ranged Attack":10, "DA":1, "Store TP":5, "Jobs":all_jobs}
Thrud_Earring = {"Name":"Thrud Earring", "STR":10, "VIT":10, "Weapon Skill Damage":3, "Jobs":["war", "pld", "drk", "bst", "sam", "drg"]}
Hattori_Earring = {"Name":"Hattori Earring +2", "PDL":9, "Throwing Skill":12, "Katana Skill":12, "Accuracy":18, "Magic Accuracy":18, "Store TP":7, "DEX":11, "AGI":11, "Jobs":["nin"]}
Hattori_Earring1 = {"Name":"Hattori Earring +1", "PDL":8, "Throwing Skill":11, "Katana Skill":11, "Accuracy":13, "Magic Accuracy":13, "Store TP":4, "Jobs":["nin"]}
Heathen_Earring = {"Name":"Heathen's Earring +2", "Attack":20, "PDL":9, "Accuracy":18, "Magic Accuracy":18, "Weapon Skill Damage":6, "STR":11, "INT":11, "Jobs":["drk"]}
Heathen_Earring1 = {"Name":"Heathen's Earring +1", "Attack":17, "PDL":8, "Accuracy":13, "Magic Accuracy":13, "Weapon Skill Damage":3, "Jobs":["drk"]}
Regal_Earring = {"Name":"Regal Earring", "INT":10, "MND":10, "CHR":10, "Magic Attack":7, "Jobs":["blm", "rdm", "sch", "geo", "whm", "brd", "blu"]}
Malignance_Earring = {"Name":"Malignance Earring", "INT":8, "MND":8, "Magic Accuracy":10, "Magic Attack":8, "Jobs":["blm", "rdm", "sch", "geo", "drk", "whm"]}
Barkarole_Earring = {"Name":"Barkarole Earring", "INT":3, "Magic Accuracy":8, "Magic Attack":8, "Jobs":["blm", "sch", "geo"]}
Wicce_Earring = {"Name":"Wicce Earring +2", "Magic Attack":9, "Magic Damage":9, "INT":11, "MND":11, "Magic Accuracy":18, "Jobs":["blm"]}
Wicce_Earring1 = {"Name":"Wicce Earring +1", "Magic Attack":8, "Magic Damage":8, "Magic Accuracy":13, "Jobs":["blm"]}
Sherida_Earring = {"Name":"Sherida Earring", "STR":5, "DEX":5, "DA":5, "Store TP":5, "Jobs":["mnk", "rdm", "thf", "bst", "rng", "drg", "dnc", "run"]}
Lethargy_Earring = {"Name":"Lethargy Earring +2", "Accuracy":0+18, "Magic Accuracy":0+18, "DA":0+7, "STR":0+11, "DEX":0+11, "Jobs":["rdm"]}
Lethargy_Earring1 = {"Name":"Lethargy Earring +1", "Accuracy":0+13, "Magic Accuracy":0+13, "DA":0+4, "Jobs":["rdm"]}
Peltast_Earring = {"Name":"Peltast's Earring +2", "PDL":9, "Subtle Blow":7, "Accuracy":18, "Magic Accuracy":18, "Crit Rate":7, "STR":11, "VIT":11, "Jobs":["drg"]}
Peltast_Earring1 = {"Name":"Peltast's Earring +1", "PDL":8, "Subtle Blow":6, "Accuracy":13, "Magic Accuracy":13, "Crit Rate":4, "Jobs":["drg"]}
Ebers_Earring = {"Name":"Ebers Earring +2", "Accuracy":18, "Magic Accuracy":18, "STR":11, "MND":11, "Jobs":["whm"]}
Ebers_Earring1 = {"Name":"Ebers Earring +1", "Accuracy":13, "Magic Accuracy":13, "Jobs":["whm"]}
Kasuga_Earring = {"Name":"Kasuga Earring +2", "Store TP":9, "Skillchain Bonus":7, "Accuracy":18, "Weapon Skill Damage":5, "STR":11, "DEX":11, "Jobs":["sam"]}
Kasuga_Earring1 = {"Name":"Kasuga Earring +1", "Store TP":8, "Skillchain Bonus":6, "Accuracy":13, "Weapon Skill Damage":3, "Jobs":["sam"]}
Arbatel_Earring = {"Name":"Arbatel Earring +2", "Magic Attack":9, "Magic Damage":9, "Magic Accuracy":18, "INT":11, "MND":11, "Jobs":["sch"]}
Arbatel_Earring1 = {"Name":"Arbatel Earring +1", "Magic Attack":8, "Magic Damage":8, "Magic Accuracy":13, "Jobs":["sch"]}
Enervating_Earring = {"Name":"Enervating Earring", "Ranged Accuracy":7, "Ranged Attack":7, "Store TP":4, "Jobs":["war", "mnk", "whm", "blm", "rdm", "thf", "pld", "drk", "bst", "brd", "rng", "sam", "nin", "drg", "smn", "blu", "cor", "pup", "dnc", "sch", "geo", "run"]}
Boii_Earring = {"Name":"Boii Earring +2", "DA":9, "Accuracy":18, "Magic Accuracy":18, "STR":11, "VIT":11, "Crit Rate":7, "Jobs":["war"]}
Boii_Earring1 = {"Name":"Boii Earring +1", "DA":8, "Accuracy":13, "Magic Accuracy":13, "Crit Rate":4, "Jobs":["war"]}
Chasseurs_Earring = {"Name":"Chasseur's Earring +2", "Accuracy":18, "Magic Accuracy":18, "STR":11, "AGI":11, "Crit Rate":7, "Jobs":["cor"]}
Chasseurs_Earring1 = {"Name":"Chasseur's Earring +1", "Accuracy":13, "Magic Accuracy":13, "Crit Rate":4, "Jobs":["cor"]}
Fili_Earring = {"Name":"Fili Earring +2", "Accuracy":18, "Magic Accuracy":18, "MND":11, "CHR":11, "Jobs":["brd"]}
Fili_Earring1 = {"Name":"Fili Earring +1", "Accuracy":13, "Magic Accuracy":13, "Jobs":["brd"]}
Skulkers_Earring = {"Name":"Skulker's Earring +2", "TA":5, "DEX":11, "AGI":11, "Accuracy":18, "Magic Accuracy":18, "Store TP":7, "Jobs":["thf"]}
Skulkers_Earring1 = {"Name":"Skulker's Earring +1", "TA":4, "Accuracy":13, "Magic Accuracy":13, "Store TP":4, "Jobs":["thf"]}
Bhikku_Earring = {"Name":"Bhikku Earring +2", "Hand-to-Hand Skill":12, "DEX":11, "STR":11, "Accuracy":18, "Magic Accuracy":18, "Store TP":7, "Jobs":["mnk"]}
Bhikku_Earring1 = {"Name":"Bhikku Earring +1", "Hand-to-Hand Skill":11, "Accuracy":13, "Magic Accuracy":13, "Store TP":4, "Jobs":["mnk"]}
Maculele_Earring = {"Name":"Maculele Earring +2", "Skillchain Bonus":7, "DEX":0+11, "AGI":0+11, "PDL":9, "Store TP":0+7, "Accuracy":0+18, "Magic Accuracy":0+18, "Jobs":["dnc"]}
Maculele_Earring1 = {"Name":"Maculele Earring +1", "Skillchain Bonus":6, "PDL":8, "Store TP":0+4, "Accuracy":0+13, "Magic Accuracy":0+13, "Jobs":["dnc"]}
Nukumi_earring = {"Name":"Nukumi earring +2", "STR":0+11, "CHR":0+11, "Axe Skill":12, "PDL":9, "Accuracy":0+18, "Magic Accuracy":0+18, "Jobs":["bst"]}
Nukumi_earring1 = {"Name":"Nukumi earring +1", "Axe Skill":11, "PDL":8, "Accuracy":0+13, "Magic Accuracy":0+13, "Jobs":["bst"]}
Azimuth_earring = {"Name":"Azimuth earring +2", "INT":0+11, "MND":0+11, "Magic Attack":9, "Magic Accuracy":0+18, "Jobs":["geo"]}
Azimuth_earring1 = {"Name":"Azimuth earring +1", "Magic Attack":8, "Magic Accuracy":0+13, "Jobs":["geo"]}
Sroda_Earring = {"Name":"Sroda Earring", "DA":7, "Jobs":["bst", "drg", "smn", "pup"]}
Chevalier_earring = {"Name":"Chevalier's earring +2", "STR":0+11, "VIT":0+11, "Magic Accuracy":0+18, "Accuracy":0+18, "DT":-7, "Jobs":["pld"]}
Chevalier_earring1 = {"Name":"Chevalier's earring +1", "Magic Accuracy":0+13, "Accuracy":0+13, "DT":-4, "Jobs":["pld"]}
Amini_earring = {"Name":"Amini earring +2", "STR":0+11, "AGI":0+11, "PDL":9, "Magic Accuracy":0+18, "Accuracy":0+18, "Crit Rate":0+7, "Jobs":["rng"]}
Amini_earring1 = {"Name":"Amini earring +1", "PDL":8, "Magic Accuracy":0+13, "Accuracy":0+13, "Crit Rate":0+4, "Jobs":["rng"]}
Karagoz_earring = {"Name":"Karagoz earring +2", "STR":0+11, "DEX":0+11, "Hand-to-Hand Skill":12, "Subtle Blow":7, "Magic Accuracy":0+18, "Accuracy":0+18, "Store TP":0+7, "Jobs":["pup"]}
Karagoz_earring1 = {"Name":"Karagoz earring +1", "Hand-to-Hand Skill":11, "Subtle Blow":6, "Magic Accuracy":0+13, "Accuracy":0+13, "Store TP":0+4, "Jobs":["pup"]}
Hashishin_earring = {"Name":"Hashishin earring +2", "STR":0+11, "INT":0+11, "Sword Skill":12, "Magic Accuracy":0+18, "Accuracy":0+18, "DA":0+7, "Jobs":["blu"]}
Hashishin_earring1 = {"Name":"Hashishin earring +1", "Sword Skill":11, "Magic Accuracy":0+13, "Accuracy":0+13, "DA":0+4, "Jobs":["blu"]}
Erilaz_earring = {"Name":"Erilaz earring +2", "Magic Evasion":11, "STR":0+11, "MND":0+11, "Magic Accuracy":0+18, "Accuracy":0+18, "DT":-7, "Jobs":["run"]}
Erilaz_earring1 = {"Name":"Erilaz earring +1", "Magic Evasion":11, "Magic Accuracy":0+13, "Accuracy":0+13, "DT":-4, "Jobs":["run"]}
Odnowa_Earring = {"Name":"Odnowa Earring +1 R15", "STR":3, "VIT":3, "Accuracy":9, "MDT":-2, "DT":-3, "Jobs":all_jobs}
Dominance_Earring = {"Name":"Dominance Earring +1 R15", "Accuracy":14, "DEX":10, "Jobs":all_jobs}
Beyla_Earring = {"Name":"Beyla Earring", "Ranged Accuracy":15, "Subtle Blow":5, "Jobs":["rng", "cor"]}