Abyssal_Beads = {"Name":"Abyssal Bead Necklace +2 R25", "Accuracy":15, "Magic Accuracy":15, "Attack":40, "Store TP":0+7, "STR":0+25, "Crit Rate":4, "PDL":0+10, "Jobs":["drk"]}
Abyssal_Beads1 = {"Name":"Abyssal Bead Necklace +1 R20", "Accuracy":10, "Magic Accuracy":10, "Attack":35, "Store TP":0+6, "STR":0+20, "Crit Rate":3, "PDL":0+8, "Jobs":["drk"]}
Baetyl_Pendant = {"Name":"Baetyl Pendant", "Magic Attack":13, "Jobs":all_jobs}
Caro_Necklace = {"Name":"Caro Necklace", "STR":6, "DEX":6, "Attack":10, "Jobs":all_jobs}
Fotia_Gorget = {"Name":"Fotia Gorget", "Weapon Skill Accuracy": 10, "ftp": 0.1, "Jobs":all_jobs}
Ninja_Nodowa = {"Name":"Ninja Nodowa +2 R25", "Accuracy": 25, "Ranged Accuracy": 25, "Store TP": 7, "DEX":15, "AGI":15, "Daken":25, "PDL":10, "Jobs":["nin"]}
Ninja_Nodowa1 = {"Name":"Ninja Nodowa +1 R20", "Accuracy": 20, "Ranged Accuracy": 20, "Store TP": 5, "DEX":12, "AGI":12, "Daken":20, "PDL":8, "Jobs":["nin"]}
Rep_Plat_Medal = {"Name":"Republican Platinum Medal", "STR":10, "Attack":30, "Ranged Attack":30, "Jobs":all_jobs}
Samurai_Nodowa = {"Name":"Samurai's Nodowa +2 R25", "Accuracy":30, "Store TP":7+7, "STR":0+25, "PDL":0+10, "Jobs":["sam"]}
Samurai_Nodowa1 = {"Name":"Samurai's Nodowa +1 R20", "Accuracy":25, "Store TP":5+6, "STR":0+20, "PDL":0+8, "Jobs":["sam"]}
Sanctity_Necklace = {"Name":"Sanctity Necklace", "Attack":10, "Ranged Attack":10, "Ranged Accuracy":10, "Magic Accuracy":10, "Magic Attack":10, "Jobs":all_jobs}
Sibyl_Scarf = {"Name":"Sibyl Scarf", "INT":10, "Magic Attack":10, "Jobs":all_jobs}
Warders_Charm = {"Name":"Warder's Charm +1 R15", "Magic Burst Damage":10, "Jobs":all_jobs}
Sorcerers_Stole = {"Name":"Sorcerer's Stole +2 R25", "INT":0+15, "MND":0+15, "Magic Burst Damage":10, "Magic Accuracy":30, "Magic Burst Accuracy":25, "Magic Attack":7, "Jobs":["blm"]}
Sorcerers_Stole1 = {"Name":"Sorcerer's Stole +1 R20", "INT":0+12, "MND":0+12, "Magic Burst Damage":8, "Magic Accuracy":25, "Magic Burst Accuracy":20, "Magic Attack":5, "Jobs":["blm"]}
Quanpur_Necklace = {"Name":"Quanpur Necklace", "Magic Attack":7, "Earth Elemental Bonus":5, "Jobs":["whm", "blm", "rdm", "brd", "smn", "blu", "pup", "sch", "geo", "run"]}
Mizukage_no_Kubikazari = {"Name":"Mizukage-no-Kubikazari", "INT":4, "MND":4, "Magic Attack":8, "Magic Burst Damage":10, "Jobs":["blm", "rdm", "sch", "geo", "whm", "brd"]}
Duelist_Torque = {"Name":"Duelist's Torque +2 R25", "Magic Accuracy":30, "INT":15, "MND":15, "Jobs":["rdm"]}
Duelist_Torque1 = {"Name":"Duelist's Torque +1 R20", "Magic Accuracy":25, "INT":12, "MND":12, "Jobs":["rdm"]}
Dragoon_Collar = {"Name":"Dragoon's collar +2 R25", "Accuracy":25, "Attack":25, "STR":0+15, "VIT":0+15, "PDL":0+10, "Crit Rate":4, "Jobs":["drg"]}
Dragoon_Collar1 = {"Name":"Dragoon's collar +1 R20", "Accuracy":20, "Attack":20, "STR":0+12, "VIT":0+12, "PDL":0+8, "Crit Rate":3, "Jobs":["drg"]}
Clerics_Torque = {"Name":"Cleric's Torque +2 R25", "INT":15, "MND":15, "Jobs":["whm"]}
Clerics_Torque1 = {"Name":"Cleric's Torque +1 R20", "INT":12, "MND":12, "Jobs":["whm"]}
Lissome_Necklace = {"Name":"Lissome Necklace", "Accuracy":8, "Store TP":4, "DA":1, "Jobs":["war", "mnk", "whm", "blm", "rdm", "thf", "pld", "drk", "bst", "brd", "rng", "sam", "nin", "drg", "smn", "blu", "cor", "pup", "dnc", "sch", "geo", "run"]}
Marked_Gorget = {"Name":"Marked Gorget", "AGI":3, "Ranged Accuracy":15, "Ranged Attack":15, "Store TP":2, "Jobs":["war", "mnk", "whm", "blm", "rdm", "thf", "pld", "drk", "bst", "brd", "rng", "sam", "nin", "drg", "smn", "blu", "cor", "pup", "dnc", "sch", "geo", "run"]}
Argute_Stole = {"Name":"Argute Stole +2 R25", "Magic Accuracy":30, "Magic Burst Damage":10, "INT":15, "MND":15, "Magic Damage":25, "Jobs":["sch"]}
Argute_Stole1 = {"Name":"Argute Stole +1 R20", "Magic Accuracy":25, "Magic Burst Damage":7, "INT":12, "MND":12, "Magic Damage":20, "Jobs":["sch"]}
Warrior_Beads = {"Name":"Warrior's Bead Necklace +2 R25", "Accuracy":25, "Attack":25, "Fencer":1, "DA":0+7, "STR":0+15, "DEX":0+15, "Jobs":["war"]}
Warrior_Beads1 = {"Name":"Warrior's Bead Necklace +1 R20", "Accuracy":20, "Attack":20, "Fencer":1, "DA":0+6, "STR":0+12, "DEX":0+12, "Jobs":["war"]}
Iskur_Gorget = {"Name":"Iskur Gorget", "Ranged Accuracy":30, "Ranged Attack":30, "Store TP":8, "Jobs":["thf", "rng", "nin", "cor"]}
Commodore_Charm = {"Name":"Commodore Charm +2 R25", "Magic Accuracy":25, "Ranged Accuracy":25, "STR":15, "AGI":15, "Magic Attack":7, "Magic Damage":25, "Jobs":["cor"]}
Commodore_Charm1 = {"Name":"Commodore Charm +1 R20", "Magic Accuracy":20, "Ranged Accuracy":20, "STR":12, "AGI":12, "Magic Attack":6, "Magic Damage":20, "Jobs":["cor"]}
Bards_Charm = {"Name":"Bard's Charm +2 R25", "Accuracy":30, "QA":3, "DEX":25, "CHR":25, "PDL":10, "Store TP":7, "Jobs":["brd"]}
Bards_Charm1 = {"Name":"Bard's Charm +1 R20", "Accuracy":20, "QA":2, "DEX":20, "CHR":20, "PDL":8, "Store TP":6, "Jobs":["brd"]}
Assassins_Gorget = {"Name":"Assassin's Gorget +2 R25", "Accuracy":25, "Magic Accuracy":25, "TA Damage%":5, "DEX":15, "AGI":15, "TA":4, "Evasion":25, "Jobs":["thf"]}
Assassins_Gorget1 = {"Name":"Assassin's Gorget +1 R20", "Accuracy":20, "Magic Accuracy":20, "TA Damage%":4, "DEX":12, "AGI":12, "TA":3, "Evasion":20, "Jobs":["thf"]}
Monk_Nodowa = {"Name":"Monk's Nodowa +2 R25", "Accuracy":30, "Kick Attacks DMG":20, "DEX":0+15, "MND":0+15, "Kick Attacks":25, "PDL":0+10, "Jobs":["mnk"]}
Monk_Nodowa1 = {"Name":"Monk's Nodowa +1 R20", "Accuracy":25, "Kick Attacks DMG":15, "DEX":0+12, "MND":0+12, "Kick Attacks":20, "PDL":0+8, "Jobs":["mnk"]}
Etoile_Gorget = {"Name":"Etoile Gorget +2 R25", "DEX":0+25, "CHR":0+25, "Accuracy":25, "Magic Accuracy":25, "Store TP":0+7, "PDL":0+10, "Jobs":["dnc"]}
Etoile_Gorget1 = {"Name":"Etoile Gorget +1 R20", "DEX":0+20, "CHR":0+20, "Accuracy":20, "Magic Accuracy":20, "Store TP":0+6, "PDL":0+8, "Jobs":["dnc"]}
Beastmaster_collar = {"Name":"Beastmaster collar +2 R25", "STR":0+15, "DEX":0+15, "Accuracy":25, "PDL":0+10, "Jobs":["bst"]}
Beastmaster_collar1 = {"Name":"Beastmaster collar +1 R20", "STR":0+12, "DEX":0+12, "Accuracy":20, "PDL":0+8, "Jobs":["bst"]}
Bagua_Charm = {"Name":"Bagua Charm +2 R25", "Magic Accuracy":30, "Jobs":["geo"]}
Bagua_Charm1 = {"Name":"Bagua Charm +1 R20", "Magic Accuracy":25, "Jobs":["geo"]}
Knight_bead_necklace = {"Name":"Knight's bead necklace +2 R25", "VIT":0+15, "MND":0+15, "Jobs":["pld"]}
Knight_bead_necklace1 = {"Name":"Knight's bead necklace +1 R20", "VIT":0+12, "MND":0+12, "Jobs":["pld"]}
Scout_Gorget = {"Name":"Scout's Gorget +2 R25", "AGI":0+25, "Accuracy":25, "Magic Accuracy":25, "Store TP":0+7, "PDL":0+10, "Jobs":["rng"]}
Scout_Gorget1 = {"Name":"Scout's Gorget +1 R20", "AGI":0+20, "Accuracy":20, "Magic Accuracy":20, "Store TP":0+6, "PDL":0+8, "Jobs":["rng"]}
Mirage_Stole = {"Name":"Mirage Stole +2 R25", "Accuracy":25, "Magic Accuracy":25, "STR":0+25, "DEX":0+25, "Store TP":0+7, "Crit Rate":0+5, "Jobs":["blu"]}
Mirage_Stole1 = {"Name":"Mirage Stole +1 R20", "Accuracy":20, "Magic Accuracy":20, "STR":0+20, "DEX":0+20, "Store TP":0+6, "Crit Rate":0+4, "Jobs":["blu"]}
Puppetmaster_Collar = {"Name":"Puppetmaster's Collar +2 R25", "Accuracy":30, "AGI":0+15, "DEX":0+15, "PDL":0+10, "Jobs":["pup"]}
Puppetmaster_Collar1 = {"Name":"Puppetmaster's Collar +1 R20", "Accuracy":25, "AGI":0+12, "DEX":0+12, "PDL":0+8, "Jobs":["pup"]}
Futhark_Torque = {"Name":"Futhark Torque +2 R25", "STR":0+15, "MND":0+15, "Magic Evasion":30, "DT":-7, "Jobs":["run"]}
Futhark_Torque1 = {"Name":"Futhark Torque +1 R20", "STR":0+12, "MND":0+12, "Magic Evasion":25, "DT":-6, "Jobs":["run"]}
Saevus_Pendant = {"Name":"Saevus Pendant +1", "Magic Accuracy":-6, "Magic Attack":18, "Jobs":["whm", "blm", "smn", "pup", "sch", "geo"]}
Clotharius_Torque = {"Name":"Clotharius Torque", "Accuracy":8, "Ranged Accuracy":8, "TA":1, "Subtle Blow":8, "Jobs":all_jobs}
Combatants_Torque = {"Name":"Combatant's Torque", "Store TP":4, "Dagger Skill":15, "Sword Skill":15, "Hand-to-Hand Skill":15, "Great Sword Skill":15, "Axe Skill":15, "Great Axe Skill":15, "Scythe Skill":15, "Polearm Skill":15, "Katana Skill":15, "Great Katana Skill":15, "Club Skill":15, "Staff Skill":15, "Marksmanship Skill":15, "Throwing Skill":15, "Archery Skill":15, "Jobs":all_jobs}
Anu_Torque = {"Name":"Anu Torque", "Store TP":7, "Attack":20, "Jobs":["mnk", "rdm", "thf", "bst", "rng", "drg", "dnc", "run"]}
Vim_Torque = {"Name":"Vim Torque +1 R15", "Store TP":10, "Accuracy":15, "Regain":20, "Jobs":["war", "pld", "drk", "sam", "drg"]}
Canto_Necklace = {"Name":"Canto Necklace +1 R15", "CHR":11+10, "Magic Accuracy":15, "Jobs":["brd"]}
Loricate_Torque = {"Name":"Loricate Torque +1 R15", "DT":-6, "Jobs":all_jobs}
Moonlight_Nodowa = {"Name":"Moonlight Nodowa", "Accuracy":25, "Zanshin":10, "Store TP":10, "Jobs":["mnk", "sam", "nin"]}
Moepapa_Medal = {"Name":"Moepapa Medal", "DEX":6, "AGI":6, "Jobs":all_jobs}
Null_Loop = {"Name":"Null Loop", "Accuracy":50, "Magic Accuracy":50, "Ranged Accuracy":50, "DT":-5, "Jobs":all_jobs}
Shulmanu_Collar = {"Name":"Shulmanu Collar", "Accuracy":20, "Attack":20, "DA":3, "Pet:Accuracy":20, "Pet:Attack":20, "Pet:DA":5, "Jobs":["bst","drg","smn","pup"]}
