
Antitail = {"Name":"Antitail +1", "Name2":"Antitail +1 R15", "Skill Type":"Throwing", "DMG":71, "Delay":252, "Ranged Attack":21, "Throwing Skill":242, "Ranged Accuracy":21, "DA":3+3, "Magic Evasion":15, "Type":"Equipment", "Jobs":["war", "thf", "rng"]}
Date = {"Name":"Date Shuriken", "Skill Type":"Throwing", "Type":"Shuriken", "DMG": 125, "Delay": 192, "Evasion":5, "Accuracy": 5, "Ranged Accuracy": 5, "Throwing Skill": 242, "DEX": 5, "AGI": 5, "Jobs":["nin"]}
Happo = {"Name":"Happo Shuriken", "Skill Type":"Throwing", "Type":"Shuriken", "DMG":  99, "Delay": 188, "Accuracy": 6, "Attack": 6, "Ranged Accuracy": 11, "Throwing Skill": 228, "Crit Rate": 2, "Jobs":["nin"]}
Seki = {"Name":"Seki Shuriken", "Skill Type":"Throwing", "Type":"Shuriken", "DMG": 101, "Delay": 192, "Attack": 13, "Store TP": 2, "Throwing Skill": 242, "Jobs":["nin"]}
Donar_Gun = {"Name":"Donar Gun", "Type":"Gun", "DMG":103, "Delay":548, "Skill Type":"Marksmanship", "Marksmanship Skill":228, "DEX":5, "AGI":5, "Thunder Elemental Bonus": 15, "Jobs":["nin", "rng", "thf", "cor"]}
Ullr = {"Name":"Ullr", "Type":"Bow", "Skill Type":"Archery", "Archery Skill":250, "DMG":178, "Delay":360, "Str":15, "DEX":15, "AGI":15, "Ranged Accuracy":40, "Ranged Attack":30, "Magic Accuracy":40, "Jobs":["war", "rdm", "thf", "pld", "drk", "bst", "rng", "sam", "nin"]}
Yoichinoyumi = {"Name":"Yoichinoyumi", "Name2":"Yoichinoyumi R15", "DMG":303+7, "Delay":524, "Ranged Accuracy":60, "Ranged Attack":45, "Archery Skill":269, "Type":"Bow", "Skill Type":"Archery", "Crit Rate":5, "Jobs":["rng", "sam"]}
Yoichinoyumi0 = {"Name":"Yoichinoyumi", "Name2":"Yoichinoyumi", "DMG":303, "Delay":524, "Ranged Accuracy":60, "Ranged Attack":45, "Archery Skill":269, "Type":"Bow", "Skill Type":"Archery", "Crit Rate":5, "Jobs":["rng", "sam"]}
Armageddon = {"Name":"Armageddon", "Name2":"Armageddon R15", "Str":0+20, "AGI":50+20, "DMG":143+8, "Delay":582, "Magic Damage":217, "Marksmanship Skill":269, "Type":"Gun", "Skill Type":"Marksmanship", "Jobs":["rng", "cor"]}
Armageddon0 = {"Name":"Armageddon", "Name2":"Armageddon", "AGI":50, "DMG":143, "Delay":582, "Magic Damage":217, "Marksmanship Skill":269, "Type":"Gun", "Skill Type":"Marksmanship", "Jobs":["rng", "cor"]}
Fomalhaut = {"Name":"Fomalhaut", "Name2":"Fomalhaut R15", "DMG":167+9, "Delay":600, "Ranged Accuracy":0+30, "Magic Accuracy":40+30, "Magic Damage":155, "Marksmanship Skill":269, "Store TP":10, "TP Bonus":500, "Type":"Gun", "Skill Type":"Marksmanship", "Jobs":["rng", "cor"]}
Fomalhaut0 = {"Name":"Fomalhaut", "Name2":"Fomalhaut", "DMG":167, "Delay":600, "Magic Accuracy":40, "Magic Damage":155, "Marksmanship Skill":269, "Store TP":10, "TP Bonus":500, "Type":"Gun", "Skill Type":"Marksmanship", "Jobs":["rng", "cor"]}
Death_Penalty = {"Name":"Death Penalty", "Name2":"Death Penalty R15", "Ranged Accuracy":30, "Magic Accuracy":30, "DMG":101+6, "Delay":480, "Magic Damage":217, "Marksmanship Skill":269, "Quick Draw Damage%":60, "Quick Draw Magic Accuracy":60, "Type":"Gun", "Skill Type":"Marksmanship", "Jobs":["cor"]}
Death_Penalty0 = {"Name":"Death Penalty", "Name2":"Death Penalty", "DMG":101, "Delay":480, "Magic Damage":217, "Marksmanship Skill":269, "Quick Draw Damage%":60, "Quick Draw Magic Accuracy":60, "Type":"Gun", "Skill Type":"Marksmanship", "Jobs":["cor"]}
Ataktos = {"Name":"Ataktos", "DMG":53, "Delay":600, "Type":"Gun", "Skill Type":"Marksmanship", "TP Bonus":1000, "Jobs":["cor", "rng"]}
Molybdosis = {"Name":"Molybdosis", "AGI":25, "DMG":103, "Delay":480, "Ranged Attack":45, "Magic Attack":30, "Type":"Gun", "Skill Type":"Marksmanship", "Marksmanship Skill":242, "Crit Damage":10, "Jobs":["cor"]}
Gandiva = {"Name":"Gandiva", "Name2":"Gandiva R15", "Type":"Bow", "Skill Type":"Archery", "Str":0+20, "DEX":50+20, "DMG":286+7, "Delay":490, "Archery Skill":269, "Jobs":["rng"]}
Gandiva0 = {"Name":"Gandiva", "Name2":"Gandiva", "Type":"Bow", "Skill Type":"Archery", "DEX":50, "DMG":286, "Delay":490, "Archery Skill":269, "Jobs":["rng"]}
Fail_not = {"Name":"Fail-not", "Name2":"Fail-not R15", "Type":"Bow", "Skill Type":"Archery", "DMG":330+7, "Delay":600, "Magic Accuracy":40+30, "Magic Damage":155, "Archery Skill":269, "Store TP":10, "TP Bonus":500, "Ranged Accuracy":0+30, "Jobs":["rng"]}
Fail_not0 = {"Name":"Fail-not", "Name2":"Fail-not", "Type":"Bow", "Skill Type":"Archery", "DMG":330, "Delay":600, "Magic Accuracy":40, "Magic Damage":155, "Archery Skill":269, "Store TP":10, "TP Bonus":500, "Jobs":["rng"]}
Accipiter = {"Name":"Accipiter", "Skill Type":"Archery", "Type":"Bow", "DMG":  94, "Delay": 524, "TP Bonus": 1000, "Jobs":["rng"]}
Annihilator = {"Name":"Annihilator", "Name2":"Annihilator R15", "Type":"Gun", "Skill Type":"Marksmanship", "DMG":143+12, "Delay":582, "Ranged Accuracy":60, "Ranged Attack":45, "Magic Damage":155, "Marksmanship Skill":269, "Store TP":0+5, "Jobs":["rng"]}
Annihilator0 = {"Name":"Annihilator", "Name2":"Annihilator", "Type":"Gun", "Skill Type":"Marksmanship", "DMG":143, "Delay":582, "Ranged Accuracy":60, "Ranged Attack":45, "Magic Damage":155, "Marksmanship Skill":269, "Jobs":["rng"]}
Gastraphetes = {"Name":"Gastraphetes", "Name2":"Gastraphetes R15", "Type":"Crossbow", "Skill Type":"Marksmanship", "DMG":176+5, "Delay":432, "Ranged Accuracy":20+30, "Magic Damage":217, "Marksmanship Skill":269, "Magic Accuracy":0+30, "Barrage Ranged Accuracy":70, "Jobs":["rng"]}
Gastraphetes0 = {"Name":"Gastraphetes", "Name2":"Gastraphetes", "Type":"Crossbow", "Skill Type":"Marksmanship", "DMG":176, "Delay":432, "Ranged Accuracy":20, "Magic Damage":217, "Marksmanship Skill":269, "Barrage Ranged Accuracy":70, "Jobs":["rng"]}
Exalted_Crossbow = {"Name":"Exalted Crossbow +1", "Type":"Crossbow", "Skill Type":"Marksmanship", "DMG":111, "Delay":227, "AGI":15, "Ranged Accuracy":37, "Marksmanship Skill":242, "Jobs":["war", "thf", "drk", "rng"]}
Mpaca_Bow0 = {"Name":"Mpaca's Bow", "Name2":"Mpaca's Bow R0", "Rank":0, "Type":"Weapon", "Skill Type":"Archery", "Str":15, "AGI":15, "DMG":271, "Delay":540, "Ranged Accuracy":40, "Ranged Attack":30, "Archery Skill":255, "True Shot":5, "Store TP":5, "Magic Accuracy":0, "Jobs":["rng"]}
Mpaca_Bow15 = {"Name":"Mpaca's Bow", "Name2":"Mpaca's Bow R15", "Rank":15, "Type":"Weapon", "Skill Type":"Archery", "Str":15, "AGI":15, "DMG":271+15, "Delay":540, "Ranged Accuracy":40, "Ranged Attack":30+30, "Archery Skill":255, "True Shot":5, "Store TP":5, "Magic Accuracy":0, "Jobs":["rng"]}
Mpaca_Bow20 = {"Name":"Mpaca's Bow", "Name2":"Mpaca's Bow R20", "Rank":20, "Type":"Weapon", "Skill Type":"Archery", "Str":15, "AGI":15, "DMG":271+17, "Delay":540, "Ranged Accuracy":40+5, "Ranged Attack":30+35, "Archery Skill":255, "True Shot":5, "Store TP":5, "Magic Accuracy":0+5, "Jobs":["rng"]}
Mpaca_Bow25 = {"Name":"Mpaca's Bow", "Name2":"Mpaca's Bow R25", "Rank":25, "Type":"Weapon", "Skill Type":"Archery", "Str":15, "AGI":15, "DMG":271+19, "Delay":540, "Ranged Accuracy":40+10, "Ranged Attack":30+40, "Archery Skill":255, "True Shot":5, "Store TP":5, "Magic Accuracy":0+10, "Jobs":["rng"]}
Mpaca_Bow30 = {"Name":"Mpaca's Bow", "Name2":"Mpaca's Bow R30", "Rank":30, "Type":"Weapon", "Skill Type":"Archery", "Str":15, "AGI":15, "DMG":271+21, "Delay":540, "Ranged Accuracy":40+15, "Ranged Attack":30+45, "Archery Skill":255, "True Shot":5, "Store TP":5, "Magic Accuracy":0+15, "Jobs":["rng"]}
Gleti_Crossbow0 = {"Name":"Gleti's Crossbow", "Name2":"Gleti's Crossbow R0", "Rank":0, "Type":"Crossbow", "Skill Type":"Marksmanship", "AGI":15, "MND":15, "DMG":115, "Delay":432, "Ranged Accuracy":40, "Ranged Attack":30, "Marksmanship Skill":255, "Store TP":5, "Crit Rate":5, "Weapon Skill Damage":10, "Magic Accuracy":0, "Jobs":["rng"]}
Gleti_Crossbow15 = {"Name":"Gleti's Crossbow", "Name2":"Gleti's Crossbow R15", "Rank":15, "Type":"Crossbow", "Skill Type":"Marksmanship", "AGI":15, "MND":15, "DMG":115+5, "Delay":432, "Ranged Accuracy":40, "Ranged Attack":30+30, "Marksmanship Skill":255, "Store TP":5, "Crit Rate":5, "Weapon Skill Damage":10, "Magic Accuracy":0, "Jobs":["rng"]}
Gleti_Crossbow20 = {"Name":"Gleti's Crossbow", "Name2":"Gleti's Crossbow R20", "Rank":20, "Type":"Crossbow", "Skill Type":"Marksmanship", "AGI":15, "MND":15, "DMG":115+6, "Delay":432, "Ranged Accuracy":40+5, "Ranged Attack":30+35, "Marksmanship Skill":255, "Store TP":5, "Crit Rate":5, "Weapon Skill Damage":10, "Magic Accuracy":0+5, "Jobs":["rng"]}
Gleti_Crossbow25 = {"Name":"Gleti's Crossbow", "Name2":"Gleti's Crossbow R25", "Rank":25, "Type":"Crossbow", "Skill Type":"Marksmanship", "AGI":15, "MND":15, "DMG":115+8, "Delay":432, "Ranged Accuracy":40+10, "Ranged Attack":30+40, "Marksmanship Skill":255, "Store TP":5, "Crit Rate":5, "Weapon Skill Damage":10, "Magic Accuracy":0+10, "Jobs":["rng"]}
Gleti_Crossbow30 = {"Name":"Gleti's Crossbow", "Name2":"Gleti's Crossbow R30", "Rank":30, "Type":"Crossbow", "Skill Type":"Marksmanship", "AGI":15, "MND":15, "DMG":115+9, "Delay":432, "Ranged Accuracy":40+15, "Ranged Attack":30+45, "Marksmanship Skill":255, "Store TP":5, "Crit Rate":5, "Weapon Skill Damage":10, "Magic Accuracy":0+15, "Jobs":["rng"]}
Earp5 = {"Name":"Earp", "Name2":"Earp V", "Type":"Gun", "Skill Type":"Marksmanship", "Marksmanship Skill":277, "DMG":162, "Delay":582, "DEX":35, "AGI":35, "Magic Accuracy Skill":277, "Crit Rate":15, "Magic Accuracy":35, "Ranged Accuracy":35, "Jobs":["rng", "cor"]}
Earp4 = {"Name":"Earp", "Name2":"Earp IV", "Type":"Gun", "Skill Type":"Marksmanship", "Marksmanship Skill":269, "DMG":151, "Delay":582, "DEX":30, "AGI":30, "Magic Accuracy Skill":269, "Crit Rate":12, "Magic Accuracy":30, "Ranged Accuracy":30, "Jobs":["rng", "cor"]}
Pinaka5 = {"Name":"Pinaka", "Name2":"Pinaka V", "Type":"Bow", "Skill Type":"Archery", "Archery Skill":277, "DMG":324, "Delay":524, "Str":35, "AGI":35, "Store TP":10, "Magic Accuracy Skill":277, "Magic Accuracy":35, "Ranged Accuracy":35, "Jobs":["rng"]}
Pinaka4 = {"Name":"Pinaka", "Name2":"Pinaka IV", "Type":"Bow", "Skill Type":"Archery", "Archery Skill":269, "DMG":309, "Delay":524, "Str":30, "AGI":30, "Store TP":7, "Magic Accuracy Skill":269, "Magic Accuracy":30, "Ranged Accuracy":30, "Jobs":["rng"]}

# Linos is pretty annoying. Define a loop to create them all here. Ignore snow_stats since you'll want Acc/Atk+15 anyway
# dusk_stats = ["Str", "DEX", "VIT", "AGI", "INT", "MND", "CHR"]
# leaf_stats = ["Weapon Skill Damage", "DA", "Crit Rate",]
# for base_stat in dusk_stats:
#     for main_stat in leaf_stats:
#         ranged.append({"Name":"Linos", "Name2":f"Linos {base_stat} {main_stat}", "Type":"Instrument", "Skill Type":"Instrument", "Accuracy":15, "Attack":15,f"{base_stat}":8, f"{main_stat}":3, "Jobs":["brd"]})
# ranged.append({"Name":"Linos", "Name2":"Linos STP QA", "Type":"Instrument", "Skill Type":"Instrument", "Accuracy":15, "Attack":15, "Store TP":4, "QA":3, "Jobs":["brd"]})
# ranged.append({"Name":"Linos", "Name2":"Linos DA QA", "Type":"Instrument", "Skill Type":"Instrument", "Accuracy":15, "Attack":15, "DA":3, "QA":3, "Jobs":["brd"]})

