Apate_Ring = {"Name":"Apate Ring", "STR":6, "DEX":6, "AGI":6, "Store TP":3, "Jobs":all_jobs}
Archon_Ring = {"Name":"Archon Ring", "Dark Elemental Bonus":5, "Jobs":all_jobs}
Begrudging_Ring = {"Name":"Begrudging Ring", "Accuracy":7, "Attack": 7, "Crit Rate":5, "DT":+10, "Jobs":all_jobs}
Beithir_Ring0 = {"Name":"Beithir Ring R0", "Rank":0, "STR":3, "DEX":3, "VIT":3, "AGI":3, "Weapon Skill Accuracy":0, "Attack":0, "Weapon Skill Damage":2, "Skillchain Bonus":0, "Jobs":["nin", "sam", "drk", "war", "mnk", "thf", "pld", "bst", "rng", "drg", "blu", "pup", "dnc"]}
Beithir_Ring15 = {"Name":"Beithir Ring R15", "Rank":15, "STR":3, "DEX":3, "VIT":3, "AGI":3, "Weapon Skill Accuracy":0+15, "Attack":0, "Weapon Skill Damage":2, "Skillchain Bonus":0, "Jobs":["nin", "sam", "drk", "war", "mnk", "thf", "pld", "bst", "rng", "drg", "blu", "pup", "dnc"]}
Beithir_Ring20 = {"Name":"Beithir Ring R20", "Rank":20, "STR":3, "DEX":3, "VIT":3, "AGI":3, "Weapon Skill Accuracy":0+15, "Attack":0+5, "Weapon Skill Damage":2, "Skillchain Bonus":0, "Jobs":["nin", "sam", "drk", "war", "mnk", "thf", "pld", "bst", "rng", "drg", "blu", "pup", "dnc"]}
Beithir_Ring25 = {"Name":"Beithir Ring R25", "Rank":25, "STR":3, "DEX":3, "VIT":3, "AGI":3, "Weapon Skill Accuracy":0+15, "Attack":0+10, "Weapon Skill Damage":2, "Skillchain Bonus":0+3, "Jobs":["nin", "sam", "drk", "war", "mnk", "thf", "pld", "bst", "rng", "drg", "blu", "pup", "dnc"]}
Beithir_Ring30 = {"Name":"Beithir Ring R30", "Rank":30, "STR":3, "DEX":3, "VIT":3, "AGI":3, "Weapon Skill Accuracy":0+15, "Attack":0+15, "Weapon Skill Damage":2, "Skillchain Bonus":0+5, "Jobs":["nin", "sam", "drk", "war", "mnk", "thf", "pld", "bst", "rng", "drg", "blu", "pup", "dnc"]}
Chirich_Ring = { "Name":"Chirich Ring +1", "Accuracy":10, "Store TP":6, "Subtle Blow":10, "Jobs":all_jobs}
Crepuscular_Ring = {"Name":"Crepuscular Ring", "Ranged Accuracy":10, "Magic Accuracy":10, "Store TP":6, "Jobs":all_jobs}
Defending_Ring = {"Name":"Defending Ring", "DT":-10, "Jobs":all_jobs}
Vocane_Ring = {"Name":"Vocane Ring +1", "DT":-8, "Jobs":all_jobs}
Dingir_Ring = {"Name":"Dingir Ring", "AGI":10, "Ranged Attack":25, "Magic Attack":10, "Recycle":10, "Jobs":["nin", "rng", "thf", "cor"]}
Epaminondas_Ring = {"Name":"Epaminondas's Ring", "Weapon Skill Damage":5, "Store TP":-10, "Jobs":all_jobs}
Epona_Ring = {"Name":"Epona's Ring", "DA":3, "TA":3, "Jobs":["nin", "mnk", "thf", "bst", "rng", "blu", "cor", "pup", "dnc", "run"]}
Flamma_Ring = {"Name":"Flamma Ring", "Accuracy":6, "Magic Accuracy":6, "Store TP":5, "Jobs":["drk", "sam", "war", "pld", "drg"]}
Gere_Ring = {"Name":"Gere Ring", "STR":10, "Attack":16, "TA":5, "Jobs":["nin", "mnk", "thf", "bst", "pup", "dnc"]}
Hetairoi_Ring = {"Name":"Hetairoi Ring", "Crit Rate":1, "TA":2, "TA Damage%":5, "Jobs":all_jobs}
Ilabrat_Ring = {"Name":"Ilabrat Ring", "DEX":10, "AGI":10, "Attack":25, "Store TP":5, "Jobs":["nin", "sam", "rdm", "mnk", "whm", "thf", "bst", "brd", "rng", "blu", "cor", "dnc", "run"]}
Karieyh_Ring = {"Name":"Karieyh Ring +1", "Weapon Skill Accuracy":10, "Weapon Skill Damage":4, "Regain":5, "Jobs":all_jobs}
Locus_Ring = {"Name":"Locus Ring", "Magic Burst Damage":5, "Magic Crit Rate":5, "Jobs":all_jobs}
Metamorph_Ring = {"Name":"Metamorph Ring +1 R15", "INT":6+10, "MND":6+10, "CHR":6+10, "Magic Accuracy":4+10, "Jobs":all_jobs}
Mujin_Band = {"Name":"Mujin Band", "Skillchain Bonus": 5, "Magic Burst Damage II":5, "Jobs":all_jobs}
Mummu_Ring = {"Name":"Mummu Ring", "Accuracy":6, "Ranged Accuracy":6, "Magic Accuracy":6, "Crit Rate":3, "Jobs":["nin", "thf", "dnc", "rng", "mnk", "cor"]}
Niqmaddu_Ring = {"Name":"Niqmaddu Ring", "STR":10, "DEX":10, "VIT":10, "QA":3, "Subtle Blow II":5, "Jobs":["drk", "sam", "war", "mnk", "drg", "pup", "run"]}
Petrov_Ring = {"Name":"Petrov Ring", "STR":3, "DEX":3, "VIT":3, "AGI":3, "DA":1, "Store TP":5, "Jobs":all_jobs}
Regal_Ring = {"Name":"Regal Ring", "STR":10, "DEX":10, "VIT":10, "AGI":10, "Attack":20, "Ranged Attack":20, "Jobs":["nin", "drk", "sam", "war", "mnk", "thf", "pld", "bst", "rng", "drg", "cor", "pup", "dnc", "run"]}
Rufescent_Ring = {"Name":"Rufescent Ring", "STR":6, "MND":6, "Weapon Skill Accuracy": 7, "Jobs":all_jobs}
Shiva_Ring1 = {"Name":"Shiva Ring +1", "INT":9, "Magic Attack":3, "Jobs":all_jobs}
Fenrir_Ring1 = {"Name":"Fenrir Ring +1", "Magic Accuracy":3, "Magic Attack":3, "Magic Damage":3, "Jobs":all_jobs}
Shukuyu_Ring = {"Name":"Shukuyu Ring", "STR":7, "Attack":15, "Jobs":all_jobs}
Sroda_Ring = {"Name":"Sroda Ring", "STR":15, "DEX":-20, "PDL":3, "Jobs":["war", "mnk", "rdm", "thf", "pld", "drk", "bst", "brd", "rng", "sam", "nin", "drg", "blu", "cor", "pup", "dnc", "run"]}
Weatherspoon_Ring = {"Name":"Weatherspoon Ring +1", "Light Elemental Bonus":11, "Magic Accuracy":13, "Jobs":all_jobs}
Freke_Ring = {"Name":"Freke Ring", "INT":10, "Magic Attack":8, "Jobs":["whm", "blm", "rdm", "sch", "geo"]}
Stikini_Ring1 = {"Name":"Stikini Ring +1", "MND":8, "Magic Accuracy":8, "Elemental Magic Skill":8, "Ninjutsu Skill":8, "Dark Magic Skill":8, "Jobs":["war", "whm", "blm", "rdm", "thf", "pld", "drk", "bst", "brd", "rng", "sam", "nin", "drg", "blu", "pup", "dnc", "sch", "run", "geo"]}
Ayanmo_Ring = {"Name":"Ayanmo Ring", "Accuracy":6, "Magic Accuracy":6, "DT":-3, "Jobs":["whm", "rdm", "brd", "blu", "run"]}
Cacoethic_Ring = {"Name":"Cacoethic Ring +1 R15", "Accuracy":11, "Ranged Accuracy":16, "DEX":0+10, "AGI":0+10, "Jobs":["war", "mnk", "whm", "blm", "rdm", "thf", "pld", "drk", "bst", "brd", "rng", "sam", "nin", "drg", "smn", "blu", "cor", "pup", "dnc", "sch", "geo", "run"]}
Ramuh_Ring1 = {"Name":"Ramuh Ring +1", "DEX":9, "Accuracy":5, "Jobs":all_jobs}
Ifrit_Ring1 = "Name":"Ifrit Ring +1", "STR":9, "Attack":5, "Jobs":all_jobs}
Leviathan_Ring1 = {"Name":"Leviathan Ring +1", "MND":9, "Magic Accuracy":3, "Jobs":all_jobs}
Titan_Ring1 = {"Name":"Titan Ring +1", "VIT":9, "Jobs":all_jobs}
Carbuncle_Ring1 = {"Name":"Carbuncle Ring +1", "CHR":9, "Magic Accuracy":4, "Jobs":all_jobs}
Garuda_Ring1 = {"Name":"Garuda Ring +1", "AGI":9, "Ranged Accuracy":5, "Jobs":all_jobs}
Gelatinous_Ring = {"Name":"Gelatinous Ring +1 R15", "PDT":-7, "MDT":+1, "VIT":0+15, "Jobs":all_jobs}
Moonlight_Ring1 = {"Name":"Moonlight Ring", "Accuracy":8, "Attack":8, "Store TP":5, "DT":-5, "Jobs":["war", "thf", "pld", "drk", "bst", "brd", "drg", "dnc", "run"]}
Mallquis_Ring = {"Name":"Mallquis Ring", "Magic Accuracy":6, "Magic Damage":12, "Jobs":["blm", "sch", "geo"]}
Cornelia_ring = {"Name":"Cornelia's ring", "Weapon Skill Accuracy":10, "Weapon Skill Damage":10, "Jobs":all_jobs}
Ephramad_ring = {"Name":"Ephramad's ring", "STR":10, "DEX":10, "AGI":10, "Accuracy":20, "Attack":20, "Ranged Accuracy":20, "Ranged Attack":20, "PDL":10, "Jobs":all_jobs}
Fickblix_ring = {"Name":"Fickblix's ring", "DA":10, "Subtle Blow":10, "Jobs":all_jobs}
Gurebu_ring = {"Name":"Gurebu-Ogurebu's ring", "MND":10, "Magic Evasion":20, "Jobs":all_jobs}
Lehko_Habhoka_ring = {"Name":"Lehko Habhoka's ring", "DEX":10, "Store TP":10, "Gear Haste":10, "Crit Rate":10, "Jobs":all_jobs}
Medada_ring = {"Name":"Medada's ring", "INT":10, "Magic Accuracy":20, "Magic Attack":10, "Jobs":all_jobs}
Ragelise_ring = {"Name":"Ragelise's ring", "VIT":10, "DT":-10, "Jobs":all_jobs}