Alber_Strap = {"Name":"Alber Strap", "Magic Attack":7, "DA":2, "Jobs":[]}
Rigorous_Grip = {"Name":"Rigorous Grip +1", "Name2":"Rigorous Grip +1 R15", "Str":4+15, "Attack":13+30, "Accuracy":3, "Jobs":[]}
Utu_Grip = {"Name":"Utu Grip", "Accuracy":30, "Attack":30, "WSC":["DEX",10], "Jobs":["drk", "sam", "war", "drg", "run"]}
Niobid_Strap = {"Name":"Niobid Strap", "Accuracy":5, "Magic Accuracy":5, "Magic Attack":5, "Jobs":[]}
Enki_Strap = {"Name":"Enki Strap", "INT":10, "MND":10, "Magic Accuracy":10, "Jobs":["blm", "rdm", "sch", "geo"]}
Khonsu = {"Name":"Khonsu", "Accuracy":30, "Magic Accuracy":30, "Gear Haste":4, "DT":-6, "Jobs":["war", "blm", "drk", "sam", "drg", "smn", "sch", "geo", "run"]}
Refined_Grip = {"Name":"Refined Grip +1", "Name2":"Refined Grip +1 R15", "DT":-3, "Jobs":["run"]}
Ammurapi_Shield = {"Name":"Ammurapi Shield", "INT":13, "MND":13, "Magic Accuracy":38, "Magic Attack":38, "Jobs":["whm", "blm", "sch", "rdm", "brd", "smn", "geo"]}
Genmei_Shield = {"Name":"Genmei Shield", "Accuracy":15, "Attack":15, "PDT":-10, "Jobs":["whm", "blm", "rdm", "brd", "smn", "blu", "sch", "geo"] }
Blurred_Shield = {"Name":"Blurred Shield +1", "Accuracy":20, "Attack":20, "Fencer":1, "Weapon Skill Damage":7, "Jobs":["war", "pld", "drk"]}
Nusku_Shield = {"Name":"Nusku Shield", "Ranged Accuracy":20, "Ranged Attack":20, "Store TP":3, "Jobs":["rng", "cor"]}
Culminus = {"Name":"Culminus", "Magic Attack":20, "Magic Damage":75, "Jobs":["whm", "blm", "rdm", "brd", "smn", "blu", "sch", "geo"]}
Sacro_Bulwark = {"Name":"Sacro Bulwark", "DT":-10, "Jobs":["war", "rdm", "pld", "bst"]}
Aegis = {"Name":"Aegis", "MDT2":-50, "Jobs":["pld"]}
Srivatsa = {"Name":"Srivatsa", "Accuracy":35, "Attack":35, "DT":-8, "Jobs":["pld"]}
Duban5 = {"Name":"Duban", "Name2":"Duban V", "VIT":35, "MND":35, "Evasion":35, "Magic Evasion":35, "MDT2":-25, "Jobs":["pld"]}
Duban4 = {"Name":"Duban", "Name2":"Duban IV", "VIT":30, "MND":30, "Evasion":30, "Magic Evasion":30, "MDT2":-20, "Jobs":["pld"]}
Ochain = {"Name":"Ochain", "VIT":25, "Jobs":["pld"]}
Diamond_Aspis = {"Name":"Diamond Aspis", "VIT":30, "Accuracy":40, "Magic Accuracy":40, "Magic Attack":30, "Evasion":30, "Magic Evasion":30, "Jobs":["war", "whm", "rdm", "thf", "pld", "bst"]}

