Eschan_Stone = {"Name":"Eschan Stone", "Accuracy":15, "Ranged Accuracy":15, "Attack":15, "Ranged Attack":15, "Magic Accuracy":7, "Magic Attack":7, "Jobs":[]}
Fotia_Belt = {"Name":"Fotia Belt", "Weapon Skill Accuracy": 10, "ftp": 25./256., "Conserve TP":7, "Jobs":[]}
Grunfeld_Rope = {"Name":"Grunfeld Rope", "STR":5, "DEX":5, "Accuracy":10, "Attack":20, "DA":2, "Jobs":[]}
Hachirin_no_Obi = {"Name":"Hachirin-no-Obi", "Jobs":[]}
Ioskeha_Belt = {"Name":"Ioskeha Belt +1", "Accuracy":17, "DA":9, "Gear Haste":8, "Jobs":["war", "drk", "sam", "drg", "run"]}
Kentarch_Belt = {"Name":"Kentarch Belt +1 R15", "STR":0+10, "DEX":0+10, "Accuracy":14, "DA":3, "Store TP":5, "Jobs":["nin", "drk", "sam", "war", "rdm", "thf", "pld", "bst", "brd", "rng", "drg", "blu", "cor", "dnc", "run"]}
Orpheus_Sash = {"Name":"Orpheus's Sash", "Elemental Bonus": 15, "Jobs":[]}
Reiki_Yotai = {"Name":"Reiki Yotai", "Accuracy":10, "Ranged Accuracy":10, "Store TP":4, "Dual Wield":7, "Jobs":["nin", "drk", "sam", "war", "mnk", "rdm", "thf", "pld", "bst", "brd", "drg", "blu", "cor", "dnc", "run"]}
Sailfi_Belt = {"Name":"Sailfi Belt +1 R15", "Gear Haste":9, "TA":2, "Attack":14, "STR":0+15, "DA":0+5, "Jobs":["nin", "drk", "sam", "war", "rdm", "thf", "pld", "bst", "rng", "brd", "drg", "blu", "cor", "dnc", "run"]}
Windbuffet_Belt = {"Name":"Windbuffet Belt +1", "Accuracy":2, "TA":2, "QA":2, "Jobs":[]}
Skrymir_Cord = {"Name":"Skrymir Cord +1", "Magic Accuracy":7, "Magic Attack":7, "Magic Damage":35, "Jobs":[]}
Sacro_Cord = {"Name":"Sacro Cord", "INT":8, "MND":8, "Magic Accuracy":8, "Magic Attack":8, "Jobs":["whm", "blm", "rdm", "blu", "sch", "geo"]}
Acuity_Belt = {"Name":"Acuity Belt +1 R15", "INT":6+10, "Magic Accuracy":15, "Jobs":["mnk", "whm", "blm", "rdm", "pld", "brd", "rng", "blu", "pup", "sch", "geo", "run"]}
Luminary_Sash = {"Name":"Luminary Sash", "MND":10, "Magic Accuracy":10, "Jobs":["mnk", "whm", "blm", "rdm", "pld", "brd", "rng", "smn", "blu", "pup", "sch", "geo", "run"]}
Yemaya_Belt = {"Name":"Yemaya Belt", "AGI":7, "Ranged Accuracy":10, "Ranged Attack":10, "Store TP":4, "Jobs":["mnk", "whm", "rdm", "thf", "bst", "brd", "rng", "sam", "nin", "blu", "cor", "dnc", "run"]}
Prosilio_Belt = {"Name":"Prosilio Belt +1", "STR":10, "Attack":28, "DA":-5, "Weapon Skill Accuracy":5, "Jobs":["war", "mnk", "whm", "blm", "rdm", "thf", "pld", "drk", "bst", "brd", "rng", "sam", "nin", "drg", "smn", "blu", "cor", "pup", "dnc", "sch", "geo", "run"]}
Kwahu_Kachina_Belt = {"Name":"Kwahu kachina belt +1", "AGI":8, "Ranged Accuracy":20, "Magic Accuracy":20, "Crit Rate":5, "Jobs":["rng", "cor"]}
Tellen_Belt0 = {"Name":"Tellen Belt R0", "Rank":0, "AGI":5, "Ranged Attack":0, "Ranged Accuracy":0, "True Shot":5, "Jobs":["rng", "cor"]}
Tellen_Belt15 = {"Name":"Tellen Belt R15", "Rank":15, "AGI":5, "Ranged Attack":0, "Ranged Accuracy":0+15, "True Shot":5, "Jobs":["rng", "cor"]}
Tellen_Belt20 = {"Name":"Tellen Belt R20", "Rank":20, "AGI":5, "Ranged Attack":0+5, "Ranged Accuracy":0+15, "True Shot":5, "Jobs":["rng", "cor"]}
Tellen_Belt25 = {"Name":"Tellen Belt R25", "Rank":25, "AGI":5, "Ranged Attack":0+10, "Ranged Accuracy":0+15, "True Shot":5, "Jobs":["rng", "cor"]}
Tellen_Belt30 = {"Name":"Tellen Belt R30", "Rank":30, "AGI":5, "Ranged Attack":0+15, "Ranged Accuracy":0+15, "True Shot":5, "Jobs":["rng", "cor"]}
Moonbow_Belt = {"Name":"Moonbow Belt +1", "STR":20, "DEX":20, "TA":8, "DT":-6, "Subtle Blow II":15, "Jobs":["mnk", "pup"]}
Gerdr_Belt = {"Name":"Gerdr Belt +1", "DEX":7, "AGI":7, "Store TP":6, "Dual Wield":4, "Crit Rate":4, "Jobs":["war", "mnk", "rdm", "thf", "pld", "drk", "bst", "brd", "sam", "nin", "drg", "blu", "cor", "dnc", "run"]}
Gerdr_Belt_NQ = {"Name":"Gerdr Belt", "DEX":5, "AGI":5, "Store TP":5, "Dual Wield":3, "Crit Rate":3, "Jobs":["war", "mnk", "rdm", "thf", "pld", "drk", "bst", "brd", "sam", "nin", "drg", "blu", "cor", "dnc", "run"]}
Cornelia_Belt = {"Name":"Cornelia's Belt", "Gear Haste":10, "STR":10, "Jobs":[]}
Goading_Belt = {"Name":"Goading Belt", "Gear Haste":5, "Store TP":5, "Jobs":[]}
Tempus_Fugit = {"Name":"Tempus Fugit +1", "Gear Haste":15, "Jobs":["war", "rdm", "thf", "pld", "drk", "bst", "brd", "rng", "sam", "nin", "drg", "blu", "cor", "dnc", "run"]}
Ninurta_Sash = {"Name":"Ninurta's Sash", "Gear Haste":7, "Subtle Blow":6, "Attack":6, "Jobs":[]}
Sweordfaetels = {"Name":"Sweordfaetels +1", "Attack":18, "Gear Haste":4, "Store TP":6, "Jobs":["war", "rdm", "thf", "pld", "drk", "bst", "brd", "rng", "sam", "nin", "drg", "blu", "cor", "dnc", "run"]}
Oneiros_Rope = {"Name":"Oneiros Rope", "Store TP":2, "Occult Acumen":20, "Jobs":[]}
Olseni_Belt = {"Name":"Olseni Belt", "Accuracy":20, "Attack":-5, "Store TP":3, "Jobs":[]}
Ponente_Sash = {"Name":"Ponente Sash", "STR":4, "AGI":9, "Ranged Attack":15, "Jobs":["rng", "cor"]}
Null_Belt = {"Name":"Null Belt", "Accuracy":30, "Magic Accuracy":30, "Evasion":30, "Ranged Accuracy":30, "Magic Evasion":30, "Magic Defense":3, "Jobs":[]}